name = "NetworkDynamic"
uuid = "2ec8e4a1-edb9-4657-8cef-4d333c164b0b"
authors = ["Statistical Network Analysis with Julia"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Network = "027a387e-e55f-4537-a155-5037e5a23bdb"

[sources]
Network = {path = "../Network.jl"}

[compat]
julia = "1.12"
Graphs = "1.9"
Network = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
